"""Data structures for Environment step information."""

from collections.abc import Sequence
from dataclasses import dataclass

from cookie_agent.core.actions import ActionIntent, ADBCommand
from cookie_agent.core.detection import Detection
from cookie_agent.core.frame import Frame
from cookie_agent.core.tracking import TrackedObject


@dataclass(frozen=True, slots=True)
class StepInfo:
    """Metadata container for debugging and replay timelines.

    Attributes:
        frame: The raw captured screen frame.
        intent: The high-level action requested.
        commands: The low-level ADB commands generated by the planner.
        detections: Raw detections before tracking.
        tracked_objects: Output from the tracker.
    """

    frame: Frame
    intent: ActionIntent
    commands: Sequence[ADBCommand]
    detections: Sequence[Detection]
    tracked_objects: Sequence[TrackedObject]
